language: rust
before_install:
    - |
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      fi
matrix:
  include:
    #- rust: stable
    #- rust: beta
    #- rust: nightly
    - rust: nightly
      dist: bionic
      addons:
        apt:
          #sources:
          #  - ubuntu-toolchain-r-test
          packages:
            - llvm-10
      env:
        - CARGO_OPTIONS="--features backtrace"
        - COVERAGE=1
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
    - |
      if [ "$COVERAGE" = "1" ] && [ -z "$TRAVIS_TAG" ]; then
        export RUSTFLAGS="-Zinstrument-coverage"
        export LLVM_PROFILE_FILE="bulletml-%42m.profraw"
      fi
    - if [ "$TRAVIS_TAG" ]; then export CARGO_OPTIONS="${CARGO_OPTIONS} --release"; fi
    - cargo build --verbose $CARGO_OPTIONS
    - cargo test --verbose $CARGO_OPTIONS
    - |
      if [ "$COVERAGE" = "1" ] && [ -z "$TRAVIS_TAG" ]; then
        llvm-profdata-10 merge -sparse bulletml-*.profraw -o bulletml.profdata;
        llvm-cov-10 export $(find target/debug/ -type f -iregex '.*/bulletml-[0-9a-f]+') -instr-profile=bulletml.profdata --format=lcov >| lcov.txt;
        bash <(curl -s https://codecov.io/bash) -f lcov.txt;
      fi
